language: java
jdk:
  - oraclejdk8

env:
# Add new projects here for them to be tested
  - PROJECT=libbudgetplex

install: cd $PROJECT && ./gradlew assemble
script: cd $PROJECT && ./gradlew check

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
