language: java
jdk:
  - oraclejdk8

env:
# Add new projects here for them to be tested
  - PROJECT=libbudgetplex

before_install: cd $PROJECT

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew javadoc
  - cd .. && .utility/initiate-publish.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

secure: "h49ofAnxiP+ypHQOYLMR+WFJPW9eWfrhwbsQYoK36hk6hEpwEutkEtSGGfkwxS04iHg1a+rErs/AjKLkiLmAYnViEbkEJq8Xq9cC0ebKfXDO+qlUCZRY+Nygw5yKxuiKIBr0/JvZh0Pkehk4dT0AVaPyMzVNZXjH90FcRxBZ13VfqjBAy20dEsexaiduIbjObN9TAU5RBF3/8XqedZGCpkTz7zILTQmEMVoXSR/rEU1TP4T4z/reW0G98idEuT03e8pL+t78/zQ9iNxhUHi37gYtdPQc+9/+Pjv4J/NiDU/vI4Sh8Lk13m1qgkTbcvfqdYq+zGbUpWo5Ryyo7/MVgxM9fQcUI/PCMLuGAeR5QLHrwGh9eBCN1LIZ6VRlGs2HpQ8yuNcR+thAcQM9TFRySAioyniawB5ZU1p0vXFX+XbnWJFJV80453Hllje1tPkQPmAm7cGWYt/p99Odi4nY8HGVjrmjEE+U7t8bcpBh/zWdgzsEjcsE7fKDjItr3Rmu76A9dh8Dhlar70pB11d9TjBHrnH7wD6NWA6CSuGrGJ6eKYuoqs5PsqHw8+wKgEzF+T9FMNq3nPvTbQF9vl2bbfhrnwQBSPfdNU+nPIv0mtA4gg4nv+wtTTCAGrYM5C2rdebN/NzKZOlfE9LNCxC08a9YS1ZJECZmMUFdPxr27W8="
